/**
 * Created by samk on 16/04/2017.
 */

export default {
  CHANGE_SIGNIN_STATUS: 'CHANGE_SIGNIN_STATUS',
  CHANGE_API_STATUS: 'CHANGE_API_STATUS',
  RECEIVE_BILL_METADATA_RESPONSE: 'RECEIVE_BILL_METADATA_RESPONSE'
}